<a href="https://colab.research.google.com/github/MattWroclaw/neural-networks/blob/main/02_basics/02_funkcje_aktywacji.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### Spis treści:
1. [Funkcje aktywacji](#a0)
    1. [Import bibliotek](#a1)
    2. [ReLU Function - Rectified Linear Unit](#a2)
    3. [Funkcja Sigmoid](#a3)
    4. [Tanh Function](#a4)
    5. [Funkcja Softmax](#a5)
  

### <a name='a0'></a> 1. Funkcje Aktywacji
#### <a name='a1'></a> 1.1 Import bibliotek

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

#### <a name='a2'></a> 1.2 ReLU Function - Rectified Linear Unit
####     $$f(x) = max(x, 0)$$


In [2]:
def max_relu(x):
    return max(x, 0.0)

In [ ]:
for i in [-10., -5., 0., 5., 10.]:
    print(max_relu(i))

0.0
0.0
0.0
5.0
10.0


In [4]:
data = np.random.randn(50)
data = sorted(data)
data

[-1.7105949874617388,
 -1.427121924839386,
 -1.2327196679339218,
 -1.1299243227485747,
 -1.018551033423933,
 -0.9930358887009165,
 -0.838103831321044,
 -0.7284881259392727,
 -0.5947186019371877,
 -0.5268771670291378,
 -0.5043456458648181,
 -0.46147573302074196,
 -0.4571837498391925,
 -0.437535592276191,
 -0.42350145877127604,
 -0.40826313193293745,
 -0.40359064258294153,
 -0.39586537911877917,
 -0.3294429241645344,
 -0.2575688607956171,
 -0.2210524555014432,
 -0.20440313022757156,
 -0.16694724891935026,
 -0.13054956620481872,
 -0.11793890091080017,
 0.026833761889226617,
 0.12496470009335152,
 0.1310728464508539,
 0.14255395000819318,
 0.144707171676938,
 0.2509683897887317,
 0.25448203887622584,
 0.2584519298852831,
 0.3084034909655775,
 0.3723289266833484,
 0.3742949716836805,
 0.46359973041423586,
 0.5333960650993084,
 0.7312893970622152,
 0.7457679884378866,
 0.8028274880002593,
 0.8764464253350869,
 0.8769435332443828,
 1.0695248839700295,
 1.0863613255796658,
 1.2545543683180411,

In [5]:
# wygenerowanie danych do wykresu
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.026834, 0.124965, 0.131073, 0.142554, 0.144707,
       0.250968, 0.254482, 0.258452, 0.308403, 0.372329, 0.374295,
       0.4636  , 0.533396, 0.731289, 0.745768, 0.802827, 0.876446,
       0.876944, 1.069525, 1.086361, 1.254554, 1.274409, 1.345073,
       1.793014, 2.046487])

In [7]:
df = pd.DataFrame({'data': data, 'max_relu_data': max_relu_data})
df.head()

data  max_relu_data
0 -1.710595            0.0
1 -1.427122            0.0
2 -1.232720            0.0
3 -1.129924            0.0
4 -1.018551            0.0

In [8]:
px.line(df, x='data', y='max_relu_data', width=700, height=400, title='ReLU Function')

#### <a name='a3'></a> 1.3 Funkcja Sigmoid
####    $$f(x) = \frac{1}{1 + e^{-x}}$$

In [9]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [10]:
for i in [-5., -3., -1., 0., 1., 3., 5.]:
    print(sigmoid(i))

0.0066928509242848554
0.04742587317756678
0.2689414213699951
0.5
0.7310585786300049
0.9525741268224334
0.9933071490757153


In [11]:
data = 3 * np.random.randn(50)
data = sorted(data)
data

[-6.484089629297341,
 -5.523442751372061,
 -5.185217708567373,
 -4.994690392979434,
 -4.724072803682203,
 -4.5132141348616805,
 -4.450130696594043,
 -3.4033038649392546,
 -3.2759591586488326,
 -2.8735549789921193,
 -2.733530035210735,
 -2.4580304265175337,
 -2.431313690421301,
 -2.159432612369794,
 -2.028144466077886,
 -1.7177412293427818,
 -1.6620068853177081,
 -1.604630608524607,
 -1.4548509294458851,
 -1.294227501080051,
 -1.2764643322527818,
 -1.0403028761714301,
 -0.6806387239774867,
 -0.5391742734801238,
 -0.40948359854544814,
 -0.3663294644920606,
 -0.3320638418833743,
 -0.2739168707920257,
 -0.13679376160488638,
 -0.1297427851818766,
 0.06893063045796609,
 0.2588511798847576,
 0.3218594476998268,
 0.3760557195795575,
 0.48499951342385084,
 0.8328424568368622,
 0.9413814960138462,
 0.95590825279675,
 1.4683565929760931,
 2.238717322301539,
 2.396218304370678,
 2.424417605184927,
 2.529560881785731,
 2.727873952439073,
 2.784578238066323,
 2.7973899776428617,
 2.931526330423058,


In [12]:
sigmoid_data = [sigmoid(x) for x in sorted(data)]
sigmoid_data

[0.0015252209189189972,
 0.003976207176903216,
 0.005567546473435833,
 0.006728242108476223,
 0.008800800812028508,
 0.010844278758976984,
 0.011542261266386643,
 0.03219237016510188,
 0.03640520329978123,
 0.053476424813804414,
 0.061023579140781145,
 0.07885327939265913,
 0.08081582645575905,
 0.10345306512151457,
 0.1162794583189715,
 0.15216233641554094,
 0.15949278038558606,
 0.167335418107767,
 0.189256125704098,
 0.21513812197678844,
 0.21815267345797468,
 0.2610915579819728,
 0.33611876093410836,
 0.36837968819541395,
 0.39903595099453243,
 0.40942824920087234,
 0.41773854353424306,
 0.43194576282711605,
 0.46585478828429855,
 0.467609726931653,
 0.5172258375385148,
 0.564353865431946,
 0.5797773468404854,
 0.5929214393260896,
 0.6189277400381991,
 0.6969556167089661,
 0.7193786286887022,
 0.7223018216990656,
 0.8128074677394108,
 0.9036728612756957,
 0.9165384753698331,
 0.9186704173189062,
 0.9261883393572806,
 0.9386515231842663,
 0.9418367495611408,
 0.9425346203476977,
 0.

In [13]:
df = pd.DataFrame({'data': data, 'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -6.484090      0.001525
1 -5.523443      0.003976
2 -5.185218      0.005568
3 -4.994690      0.006728
4 -4.724073      0.008801

In [14]:
px.line(df, x='data', y='sigmoid_data', width=700, height=400, title='Sigmoid Function')

#### <a name='a4'></a> 1.4 Tanh Function

####   $$tanh (x) = \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [15]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [16]:
data = 2 * np.random.randn(100)
data = sorted(data)
data

[-4.533102954207056,
 -3.6443012201988143,
 -3.508405361818773,
 -3.2877401474692225,
 -2.967859745552768,
 -2.934798322742652,
 -2.827572652503229,
 -2.6159507920617537,
 -2.579601765423305,
 -2.525162222821531,
 -2.469216963173834,
 -2.281195464378686,
 -2.2742903991844456,
 -2.2302640913783955,
 -2.208457343792917,
 -2.063721849163881,
 -2.031291828137534,
 -2.02283116078151,
 -1.9854556791446019,
 -1.9761858803809815,
 -1.9643160727683107,
 -1.9199746957629242,
 -1.8149101347840673,
 -1.8024575413968429,
 -1.7951462575027817,
 -1.6794727166324361,
 -1.354527872102833,
 -1.3449567477301265,
 -1.323786402080237,
 -1.2785453734258179,
 -1.2157282327047143,
 -1.1449570774281235,
 -1.1127540596920271,
 -1.0832933039838133,
 -1.066690821394177,
 -1.02217145811125,
 -1.0029090181492575,
 -0.9623498709064006,
 -0.8931320620351502,
 -0.8700938114830066,
 -0.8533932950800879,
 -0.8437307331209575,
 -0.8412370561941663,
 -0.7936139038583929,
 -0.7146352453018573,
 -0.7130263690723039,
 -0.700

In [17]:
tanh_data = [tanh(x) for x in sorted(data)]
tanh_data

[-0.9997690187974799,
 -0.9986343684847785,
 -0.9982082452319844,
 -0.9972156094974725,
 -0.9947272969928859,
 -0.994367880808443,
 -0.9930254779723758,
 -0.9893700897876448,
 -0.988573112843383,
 -0.987267074485302,
 -0.9857703434831994,
 -0.9793414651028575,
 -0.979057197131411,
 -0.9771515271260474,
 -0.9761451242248115,
 -0.9682636304117122,
 -0.9661729555608748,
 -0.9656056139196004,
 -0.9629854737868172,
 -0.9623058927507694,
 -0.9614178120205672,
 -0.9579152209802098,
 -0.9483284767117391,
 -0.9470599205300976,
 -0.9463010505499038,
 -0.9327930945644929,
 -0.8751177852558203,
 -0.8728576645099397,
 -0.867722467838198,
 -0.8560968709151384,
 -0.8383895577929531,
 -0.8160765636838317,
 -0.8050337530603141,
 -0.7944171837544728,
 -0.7882112236548169,
 -0.7707495053004904,
 -0.7628131647957851,
 -0.7453231999354207,
 -0.7129372723815545,
 -0.7014217910085151,
 -0.6928380510716418,
 -0.6877800523960264,
 -0.6864637330024564,
 -0.6604514349750646,
 -0.6135752486086874,
 -0.61257108297

In [18]:
df = pd.DataFrame({'data': data, 'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -4.533103  -0.999769
1 -3.644301  -0.998634
2 -3.508405  -0.998208
3 -3.287740  -0.997216
4 -2.967860  -0.994727

In [19]:
px.line(df, x='data', y='tanh_data', width=700, height=400, title='Tanh Function')

#### <a name='a5'></a> 1.5 Softmax Function

####   $$S(x_i)=\frac{e^{x_{i}}}{\sum_{j=1}^{N}e^{x_j}},\ \ dla\ i = 1,...,N$$

####   $$S(x_1)=\frac{e^{x_{1}}}{\sum_{j=1}^{N}e^{x_j}}$$

In [22]:
def softmax(x):
    e_x = np.exp(x)
    denominator = np.sum(e_x, axis=1)
    denominator = denominator[:, np.newaxis]
    return e_x / denominator

In [23]:
data = np.random.randn(4, 5)
data

array([[-6.237599e-01, -1.353234e-01, -3.184904e-01, -8.535905e-01,
         3.600748e-01],
       [-7.727761e-01, -1.319506e+00,  1.770642e+00,  9.507840e-01,
         1.172339e+00],
       [-4.099036e-01, -6.947444e-01, -2.494031e-01,  2.043388e+00,
         2.410072e-02],
       [ 1.463200e+00, -9.464648e-02,  1.568897e+00,  7.921393e-01,
         1.947681e-03]])

In [24]:
result = softmax(data)
result

array([[0.134118, 0.218581, 0.181997, 0.106579, 0.358725],
       [0.037174, 0.021518, 0.472963, 0.208337, 0.260008],
       [0.062126, 0.046727, 0.072943, 0.722316, 0.095888],
       [0.326244, 0.068704, 0.362616, 0.166765, 0.075671]])

In [25]:
result.sum(axis=1)

array([1., 1., 1., 1.])