<a href="https://colab.research.google.com/github/MattWroclaw/neural-networks/blob/main/02_basics/03_entropia_funkcje_straty.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### Funkcje Straty - Loss Function:
1. [Entropia rozkładu prawdopodobieństwa](#a0)
2. [Binarna entropia krzyżowa - Binary Crossentropy](#a1)
3. [Kategoryczna entropia krzyżowa - Categorical Crossentropy](#a0)

#### <a name='a0'></a> 1. Entropia rozkładu prawdopodobieństwa
$$Entropia = - \sum_{i}p_{i} * log(p_{i})$$
Gdzie $p_{i}$ to prawdopodobieństwo zajścia $i$-tego zdarzenia. Entropia charakteryzuje mozliwośc oddawania informacji przez żródło. Inaczej jest to miara nieokreśloności/niepewności. Średnie zdziwienie (wartość oczekiwana zdziwienia)

Pokazuje czystość zbioru: np. czy jest dobrze sklasyfikowana dana grupa.

Entropia jest miarą niepewności lub nieokreśloności w zbiorze danych. Im wyższa entropia, tym większa niepewność. Na przykład, jeśli mamy zbiór danych, w którym wszystkie wartości są takie same, to entropia będzie równa zero, ponieważ nie ma żadnej niepewności co do wartości danych. Jeśli jednak mamy zbiór danych, w którym wartości są bardzo różne, to entropia będzie wysoka, ponieważ istnieje duża niepewność co do wartości danych.  

 W uczeniu maszynowym entropia jest używana jako miara jakości modelu. Na przykład, jeśli mamy model, który przewiduje prawdopodobieństwo wystąpienia określonego zdarzenia, to entropia może być użyta do pomiaru tego, jak dobrze model przewiduje prawdopodobieństwo.  



In [ ]:
# Przygotowanie środowiska do pracy z Tensorflow 2.0.
# Jeśli otrzymasz błąd podczas instalacji Tensorflow uruchom tę komórkę raz jeszcze.

!pip uninstall -y tensorflow
!pip install -q tensorflow==2.0.0

Found existing installation: tensorflow 2.0.0
Uninstalling tensorflow-2.0.0:
  Successfully uninstalled tensorflow-2.0.0


In [1]:
import tensorflow as tf
tf.__version__

'2.17.0'

In [2]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

def entropy(labels, base=None):
    from math import log, e
    n_labels = len(labels)

    if n_labels <= 1:
        return 0

    value, counts = np.unique(labels, return_counts=True)
    probs = counts / n_labels
    n_classes = np.count_nonzero(probs)

    if n_classes <= 1:
        return 0

    ent = 0.

    base = e if base is None else base
    for i in probs:
        ent -= i * log(i, base)
    return ent


labels = [1,3,5,2,3,5,3,2,1,3,4,5]
entropy(labels)

1.5171063970610277

In [3]:
labels = [3, 3, 3, 3, 3, 3, 3]
entropy(labels)

0

In [4]:
labels = [300, 3, 3, 3, 3, 3, 3]
entropy(labels)

0.410116318288409

In [11]:
labels = [30000000, 3, 3, 3, 3, 3, 3]
entropy(labels)

0.410116318288409

#### <a name='a1'></a> 2. Binarna entropia krzyżowa - Binary Crossentropy
$$Binary\ CrossEntropy = - \frac{1}{N}\sum_{i=1}^{N}(y_{i}*log(p(y_{i})) + (1-y_{i}) * log(1-p(y_{i}))$$  

**To jest dla klas binarnych.**


In [5]:
from tensorflow.keras.losses import binary_crossentropy

y_true = np.array([1, 0, 1, 1, 0, 1], dtype='float')
y_pred = np.array([0, 0, 1, 1, 0, 1], dtype='float')

binary_crossentropy(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=2.6863493584930573>

In [6]:
#  teraz przekonajmy się co będzie jak wszystko będzie się zgadzać

y_true = np.array([1, 0, 1, 1, 0, 1], dtype='float')
y_pred = np.array([1, 0, 1, 1, 0, 1], dtype='float')

binary_crossentropy(y_true, y_pred)

#  Dążymy do minimalizacji entropii

<tf.Tensor: shape=(), dtype=float64, numpy=1.0000000494736474e-07>

#### <a name='a2'></a> 3. Kategoryczna entropia krzyżowa - Categorical Crossentropy
$$Categorical\ CrossEntropy= - \sum_{i}y_{i} * log(p(y_{i})) $$

**To jest dla wieloklasowych**

In [7]:
from tensorflow.keras.losses import categorical_crossentropy

y_true = np.array([1, 0, 1, 1, 2, 0, 1, 1, 2], dtype='float')
y_pred = np.array([0, 0, 1, 1, 2, 0, 1, 2, 2], dtype='float')

categorical_crossentropy(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=30.23015636684835>

In [9]:
y_true = np.array([0, 0, 1, 1, 2, 0, 1, 1, 2], dtype='float')
y_pred = np.array([0, 0, 1, 1, 2, 0, 1, 1, 2], dtype='float')

categorical_crossentropy(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=13.862943611198904>